version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
        ports:
            - "8080:80"
        depends_on:
            -   app
        container_name: project_nginx
        networks:
            - app-network

    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            -   ./:/var/www
        depends_on:
            - db
        container_name: project_app
        ports:
            -   "2525:2525"
        networks:
            - app-network
    db:
        image: mysql:8.0.12
        restart: unless-stopped
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: lara
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:3306"
        tty: true
        container_name: project_db
        networks:
            - app-network


#Docker Networks
networks:
        app-network:
                driver: bridge

